student:
  id: 1
  name: mmm
  age: 18
spring:
  datasource:
    url: jdbc:mysq://127.0.0.1
    username: my
    password: mymy
dbtypes:
  name:
    - mysql
    - sqlserver
    - db1
  map:
    k1: v1
    k2: v2
    k3: v3
logging:
  level:
    root: info
    org.example.stringiocdemo: trace
  file:
    # name 优先级高于 path
    path: logger
    name: springboot.log
  logback:
    rollingpolicy:
      max-file-size: 20MB
