student:
  id: 1
  name: mmm
  age: 18
spring:
  datasource:
    url: jdbc:mysq://127.0.0.1
    username: my
    password: mymy
dbtypes:
  name:
    - mysql
    - sqlserver
    - db1
  map:
    k1: v1
    k2: v2
    k3: v3